import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import HeaderExterno from "@/components/header/externo/header";
import "./globals.css";

import resolveConfig from "tailwindcss/resolveConfig";
import tailwindConfig from "../../tailwind.config";
import { useMemo } from "react";
import { ConfigProvider } from "antd";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = useMemo(() => resolveConfig(tailwindConfig), []);

  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} antialiased h-screen bg-[url('/images/bg/background-principal.webp')] bg-no-repeat bg-top`}
        style={{ backgroundSize: "100% 900px", backgroundPositionY: "-45px" }}>

        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#1890ff",
              borderRadius: 8,
            },
            components: {
              Menu: {
                colorText: config.theme.colors.primary,
                colorBgContainer: config.theme.colors.transparent,
              },
              Button: {
                colorPrimary: config.theme.colors.primary,
                fontWeight: "bold",
              },
              Card: {
                colorBgContainer: config.theme.colors.quinary,
              }
            },
          }}
        >
          <HeaderExterno />
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}