import type { Metadata } from "next";
import { Inter, Roboto_Mono, Montserrat } from "next/font/google";
import HeaderExterno from "@/components/header/externo/header";
import "./globals.css";

import resolveConfig from "tailwindcss/resolveConfig";
import tailwindConfig from "../../tailwind.config";
import { useMemo } from "react";
import { ConfigProvider, App, Layout } from "antd";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["200", "300", "400", "600", "700", "800", "900"],
  variable: "--font-montserrat",
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config = useMemo(() => resolveConfig(tailwindConfig), []);

  return (
    <html lang="pt-br">
      <body
        className={`${inter.variable} ${montserrat.variable}  antialiased h-screen bg-[url('/images/bg/background-principal.webp')] bg-cover  bg-[0_-120px]  2xl:bg-right bg-no-repeat bg-left  ocultar-scroll   
`}

      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: config.theme.colors.primary,
              colorPrimaryHover: config.theme.colors.quaternary,
              borderRadius: 8,
            },
            components: {
              Menu: {
                colorText: config.theme.colors.primary,
                colorBgContainer: config.theme.colors.transparent,
              },
              Button: {
                colorPrimary: config.theme.colors.primary,
                fontWeight: "bold",
                defaultHoverBg: config.theme.colors.primary,
                defaultHoverColor: config.theme.colors.primary,
              },
              Card: {
                colorBgContainer: config.theme.colors.quinary,
              },
            },
          }}
        >
          <App>

            <HeaderExterno />

            {children}

          </App>
        </ConfigProvider>
      </body>
    </html>
  );
}